config/routes.rb
Rails.application.routes.draw do
  get "/", to: "application#home", as: "root"

  get "/admin/analytics", to: "users#analytics", as: "analytics"

  get "/users/:id/downgrade_plan", to: "users#downgrade_plan", as: "downgrade"
  patch "/users/:id/downgrade_plan", to: "users#downgrade_plan"
  get "/users/:id/delete", to: "users#delete", as: "delete_user"
  get "/users/:id/goodbye", to: "users#goodbye", as: "goodbye"
  resources :trainers
  resources :lessons
  resources :class_plans
  resources :plans
  resources :users

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auto_login' => 'sessions#create_from_signup'


  # These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :plan
  has_many :enrollments
  has_many :lessons, through: :enrollments
  has_secure_password
  validates :username, uniqueness: true
  validates :name,:username, presence: true

  def eligible_for_more_lessons?
    self.lessons.count < self.plan.lesson_limit
  end

  def enroll(lesson)
    if self.eligible_for_more_lessons? && !lesson.full? && !self.time_conflict?(lesson)
      self.lessons << lesson
    end
  end

  def lesson_names
    self.lessons.map { |l| l.name}
  end


  def enrolled?(lesson)
    self.lessons.include?(lesson)
  end

  def unenroll(lesson)
    if self.enrolled?(lesson)
      Enrollment.find_by(user_id: self.id, lesson_id: lesson.id).destroy
    end
  end

  # def eligible_lessons
  #   self.plan.lessons
  # end

  def trainers
    self.lessons.map{|l| l.trainer.name}
  end

  def schedule
    self.lessons.map{|l| l.time}
  end

  def time_conflict?(lesson)
    self.schedule.include?(lesson.time)
  end

  def upgrade_plan
    if self.plan.level < Plan.maximum.level
      self.plan = plan.next_level
      self.save
    end
    self.plan
  end

  def downgrade_plan
    if self.plan.level > 1
      self.plan = Plan.find_by(level: (self.plan.level-1))
      self.save
    end
    self.plan
  end #downgrade_plan




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:index, :new, :create]
  before_action :session_match, only: [:edit, :update, :downgrade_plan, :delete, :goodbye]


  def downgrade_plan
      @user = User.find(params[:id])
      if params[:user] || params[:commit]
        if params[:user] && params[:user][:lessons]
          @user.unenroll(Lesson.find(params[:user][:lessons]))
        end
        @user.plan = @user.plan.prev_level
        @user.save
        redirect_to @user
        return
      end
    # if params[:loop]
    #   @loop = params[:loop].to_i + 1
    #   if @loop > 5
    #     @user.plan = user.plan.prev_level
    #     redirect_to @user
    #     return
    #   end
    # else
    #   @loop = 1
    #   render :downgrade_plan
    #   return
    # end
    # redirect_to downgrade_path(request.parameters)#controller: "Users", action: "downgrade_plan", loop: @loop+1
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @plans = Plan.all
    @lessons = Lesson.all.select{|l| !@user.lessons.include?(l) && !l.full?}
  end

  def create
    # byebug
    @user = User.new(user_params)
    if !@user.valid?
      # byebug   #we placed this here because during validation of name existance or username uniqueness, the app would have error
      # render :new
      redirect_to new_user_path, :flash => {:error => @user.errors.full_messages} #we redirect rather than render because render + collection_select was causing an error
      return
    end
    @user.enroll(Lesson.find(params[:user][:lessons]))
    if @user.save
    # redirect_to @user
      redirect_to url_for(:controller => :sessions, :action => :create_from_signup, :username => params[:user][:username], :password => params[:user][:password])
    else
      render :new
    end #if
  end #end create

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @lessons = Lesson.all.select{|l| !@user.lessons.include?(l) && !l.full?}
    @plans = @user.plan.higher_plans
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]

    if params[:commit] && params[:commit] == "Update User"

      if params[:user][:plan_id] && params[:user][:plan_id] != ""
        @user.plan = Plan.find(params[:user][:plan_id])
      end
      if params[:user][:lessons] && params[:user][:lessons] != ""
        @user.enroll(Lesson.find(params[:user][:lessons]))
      end
      if params[:user][:unenroll_lessons] && params[:user][:unenroll_lessons] != ""
        @user.unenroll(Lesson.find(params[:user][:unenroll_lessons]))
      end
      if params[:user][:admin] && params[:user][:admin] == "1"
        @user.admin = true
      end

    elsif params[:commit] && params[:commit] == "Change Password"
      if @user.authenticate(params[:user][:current_password]) && params[:user][:new_password] == params[:user][:confirm_new_password]
        #@user.password_digest = BCrypt::Password.create()
        @user.password = params[:user][:new_password]
      else
        redirect_to edit_user_path(@user)
        return
      end

    end
    @user.save
    redirect_to @user
  end

  def delete
    @user = User.find(params[:id])
  end

  def goodbye
    @user = User.find(params[:id])
    @user.destroy
  end

  def analytics
    #if current_user.admin
    @basic_users = User.all.select{|u| u.admin.nil?}
    @plans = Plan.all
    if current_user.admin
      render :analytics
      return
    else
      redirect_to "/"
      return
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :plan_id,:password, :password_confirmation, :username, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/analytics.html.erb
<h1>Planet Flatiron Analytics</h1>

<h2>Total customer base: <%=@basic_users.count%></h2>
  <%@plans.each do |plan|%>
    <p>Ratio of customers who are enrolled in <%=plan.name%> plan: <%=((plan.users.count.to_f / @basic_users.count)*100).round(2)%>% (<%=plan.users.count%>/<%=@basic_users.count%>)</p>
  <%end%>

<h2>Total number of trainers: <%=Trainer.all.count%></h2>
<h3>Trainers sorted by revenue generation:</h3>

  <%Trainer.sorted_popularity.each do |t|%>
    <%=t[0].name%> teaches <%=t[1]%> customers and generates $<%=t[0].trainer_revenue%><br>
  <%end%>
  <br>Note that the above may not sum to the total gym revenue, as some users who are signed up for a plan, may not be enrolled in any lessons.

<h2>Total revenue: $<%=Plan.total_revenue%></h2>

  <%@plans.each do |plan|%>
    <p>Total revenue being generated by <%=plan.name%> plan: $<%=plan.plan_revenue%></p>
  <%end%>

<!--  -->
<h2>Revenue Forecasting</h2>
Revenue generated by increasing fees per plan
<h4>Forecasting revenue: $<span id="forcastTotal"><%=Plan.total_revenue%></span></h4>

  <%@plans.each do |plan|%>
    <p> Revenue <%=plan.name%> plan: $<span id="forcastDisplay<%=plan.level%>"><%=plan.plan_revenue%></span><span id="forcastDifference<%=plan.level%>"></span>
        <input type="text" id="futureValue<%=plan.level%>" value="<%=plan.price%>">
        <!-- <input type="submit" id="futureValueSubmit<%=plan.level%>" value="See Forcast"> -->
        <!-- <button type="button" name="button" onclick="displayUpdate(< %=plan.level%>)"></button> -->
        <button type="button" name="button" onclick="displayUpdate('<%=plan.level%>','<%=plan.price%>','<%=plan.users.count%>')"></button>
    </p>
  <%end%>


<script type="text/javascript">
function displayUpdate(level,price,userCount){
  console.log("Hello");
  console.log(<%= User.all.count%>)
  console.log(level);
  console.log(price);
  console.log(userCount);
  console.log(<%=Plan.first.revenue_forecast(5)%>)

  planInput="futureValue"+level.toString()
  newPrice = document.getElementById(planInput).value
  console.log("price increase is:" +newPrice)

  newRevenue = userCount * newPrice
  difference = newRevenue - (userCount * price)
  console.log("newRevenue is :" + newRevenue +" and difference is: " +difference)

  forcastDisplay = "forcastDisplay" + level
  document.getElementById(forcastDisplay).textContent=newRevenue;
  forcastDifference = "forcastDifference" + level
  if (difference >=0) {
    sign = "+"
  } else {
    sign = "-"
  }
  document.getElementById(forcastDifference).textContent=" (" + sign + "$" + Math.abs(Number(difference)).toString() +")"
  oldTotal=document.getElementById("forcastTotal").innerText
  console.log("old total is "+ oldTotal)

  newTotal = Number(document.getElementById("forcastDisplay1").innerText) + Number(document.getElementById("forcastDisplay2").innerText) + Number(document.getElementById("forcastDisplay3").innerText)

  //newTotal = difference + Number(oldTotal)
  console.log("new total is "+ newTotal)
  document.getElementById("forcastTotal").textContent = newTotal


}



  // var plans = <%= @plans.map{|p| [p.level,p.price]} %>
  // plans.forEach(function(plan){
  //   console.log(plan)
  //   planName="futureValueSubmit"+plan[0].toString()
  //   // console.log(planName)
  //    // document.getElementById(planName).addEventListener("click", displayUpdate(plan[0]));
  //
  // })
  //

  // array1.forEach(function(element) {
  //   console.log(element);
  // });

</script>

app/views/users/delete.html.erb
<h1>Are you really sure you want to delete your account?</h1><br>
<%=link_to "I changed my mind", @user%><br><br>

<%=link_to "Improving myself isn't really my thing", goodbye_path%>

app/views/users/downgrade_plan.html.erb
<h1>Are you really sure you want to downgrade?</h1><br>
<%=link_to "I changed my mind", @user%><br><br>

<%=form_with model: @user, url: downgrade_path do |f|%>
  <%if @user.lessons.count >= @user.plan.lesson_limit%>
    <%=f.label :remove_lesson%>
    <p>You must remove at least one lesson to downgrade your account successfully:</p>
    <%=f.collection_select :lessons, @user.lessons, :id, :name_date_trainer%>
  <%end%>
  <%=f.submit "Yeah I hate being healthy"%>
<%end%>

app/views/users/edit.html.erb
<h1><%=@user.name%>'s account settings</h1>

<div id="wrap">
   <div id="content">

<%=form_with model: @user do |f|%>

  <%if current_user.admin%>
    <%=f.label "Toggle #{@user.name}'s administrator status"%>
    <%=f.check_box :admin, {}, 1, nil%><p></p>
  <%end%>
  <%=f.label :name%> <br>
  <%=f.text_field :name%><p></p>

  <%if @user.plan.level != Plan.maximum.level%>
    <%=f.label :upgrade%><br>
    <%=f.collection_select :plan_id, @plans, :id, :name_for_collection_select, :include_blank => "Click here to select a plan to upgrade to"%><p></p>
  <%end%>

  <%if @user.plan.lesson_limit > @user.lessons.count%>
    You have <%=pluralize((@user.plan.lesson_limit - @user.lessons.count), "available lesson slot")%>.<br>
    Enroll in another?<br>
    <%=f.collection_select :lessons, @lessons, :id, :name_date_trainer, :include_blank => true%><p></p>
  <%end%>

  <%if @user.lessons.count > 0%>
    Would you like to unenroll from any of your scheduled lessons? <br>
    <%=f.collection_select :unenroll_lessons, @user.lessons, :id, :name_date_trainer, :include_blank => true%>
  <%end%>

  <%=f.submit%><br><br>

<%end%>

<%=link_to "Cancel changes and return to profile.", @user%><br><br><br>

<%if current_user.id == @user.id%>
  <h3>Password change form</h3>
  <%=form_with model: @user do |f|%>
    <%=f.label :current_password%><br>
    <%=f.password_field :current_password%><p></p>

    <%=f.label :new_password%><br>
    <%=f.password_field :new_password%><p></p>

    <%=f.label :confirm_new_password%><br>
    <%=f.password_field :confirm_new_password%><p></p>

    <%=f.submit "Change Password"%><br><br><p></p>
  <%end%>
<%end%>

<%if @user.plan.level > 1%>
  <p> <%=link_to "Downgrade your account? (pls no)", downgrade_path%><br></p>
<%end%>

<%=link_to "Delete your account? (#{"also " if @user.plan.level > 1}pls no)", delete_user_path%>

</div>
</div>

app/views/users/goodbye.html.erb
<h1> I see how it is. We didn't need you anyway. </h1>
<p><%=link_to "Click here to return to user list", users_path%></p>

app/views/users/index.html.erb
<h1>List of Gym Members</h1>

<!-- <ul> -->
<div id="wrap">
   <div id="content">
<%@users.each do |user|%>
  <li><%=link_to user.name, user%></li>
<%end%>
</div>
</div>
<!-- </ul> -->

app/views/users/new.html.erb
<div id="wrap">
   <div id="content">
   <!-- This will be centered -->
   <h1>Signup </h1>

   <% if flash[:error]%>
     <% flash[:error].each do |attr, msg| %>
       <li style="color:red;background-color:black">   <%= "#{attr} #{msg}" if @user.errors[attr].first == msg %> </li>
     <% end %>
   <% end %>

   <%= form_for :user, url: '/users' do |f| %>
     Your Name: <br> <%= f.text_field :name %> <br> <p></p>
     Loginname: <br><%= f.text_field :username %><br> <p></p>
     Password: <br><%= f.password_field :password %><br> <p></p>
     Password Confirmation:<br> <%= f.password_field :password_confirmation %><br><p></p>
     <%=f.label :plan%>
     Select a membership plan:<br> <%=f.collection_select :plan_id, @plans, :id, :name_for_collection_select%><br><p></p>
     Select one lesson to get started:<br> <%=f.collection_select :lessons, @lessons, :id, :name_date_trainer%><br><p></p>
     <%= f.submit "Submit" %>

   <% end %>

   </div>
</div>

<!--
Parameters: {"utf8"=>"✓", "authenticity_token"=>"176bA47aUmeNdt7+nUhHHWX//nBVA9OiaBQajllipRD6/sN2gYYbMSwKdCtPZG7vfNzYL8RXzqR9ElSwjTUqFw==", "user"=>{"name"=>"Joe", "username"=>"JoeCool", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "plan_id"=>"3", "lessons"=>"1"}, "commit"=>"Submit"}
Unpermitted parameters: :username, :password, :password_confirmation, :lessons -->
<!-- <iframe width="1" height="1" src="http://www.youtube.com/embed/
yWUPMd9fJOs?autoplay=1&cc_load_policy=1" frameborder="0"
allowfullscreen></iframe> -->
<!-- marshemmelo short above long below -->
<iframe width="1" height="1" src="http://www.youtube.com/embed/
ALZHF5UqnU4?autoplay=1&cc_load_policy=1" frameborder="0"
allowfullscreen></iframe>
<!-- bass and tweeters -->
<!-- <iframe width="1" height="1" src="http://www.youtube.com/embed/
af4Nra1tdHc?autoplay=1&cc_load_policy=1" frameborder="0"
allowfullscreen></iframe> -->
<!-- darude -->
<!-- <iframe width="1" height="1" src="http://www.youtube.com/embed/
hNPTubBj9Iw?autoplay=1&cc_load_policy=1" frameborder="0"
allowfullscreen></iframe> -->

app/views/users/show.html.erb
<h1>Gym Member <%=@user.name%></h1>

<h3>Currently signed up for the <%=@user.plan.name%> tier plan</h3>

<%if @user.lessons.count == 0 %>
  <h4><%=@user.name%> is not currently enrolled in any lessons. Click below to enroll!</h4>
<%else%>
  <h4><%=@user.name%> is enrolled in the following lessons:</h4>
  <!-- <ul> -->
    <%@user.lessons.each do |l|%>
      <li><%=link_to l.name_date_trainer, l%></li>
    <%end%>
  <!-- </ul> -->
<%end%>

<%if session[:user_id] == @user.id || current_user.admin%>
  <br><%=link_to "Account settings and changes", edit_user_path(@user)%>
<%end%>

<!-- darude -->
<iframe width="1" height="1" src="http://www.youtube.com/embed/
hNPTubBj9Iw?autoplay=1&cc_load_policy=1" frameborder="0"
allowfullscreen></iframe>