config/routes.rb
Rails.application.routes.draw do
  get "/", to: "application#home", as: "root"

  get "/admin/analytics", to: "users#analytics", as: "analytics"

  get "/users/:id/downgrade_plan", to: "users#downgrade_plan", as: "downgrade"
  patch "/users/:id/downgrade_plan", to: "users#downgrade_plan"
  get "/users/:id/delete", to: "users#delete", as: "delete_user"
  get "/users/:id/goodbye", to: "users#goodbye", as: "goodbye"
  resources :trainers
  resources :lessons
  resources :class_plans
  resources :plans
  resources :users

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auto_login' => 'sessions#create_from_signup'


  # These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :enrollments
  has_many :users, through: :enrollments
  belongs_to :trainer

  def self.most_popular
    popular = []
    count = 0
    self.all.each do |l|
      if l.users.count > count
        popular = []
        popular << l
        count = l.users.count
        # [popular]
      elsif l.users.count == count
        popular << l
      end
    end
    popular
  end

  def full?
    self.users.count >= self.capacity
    #used >= just in case of overbooking somehow
  end

  def name_date_trainer
    "#{self.name} on #{self.time.split(" ")[0]}s at #{self.time.split(" ")[1]} with #{self.trainer.name}"
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    params[:open_select] ? @is_open = params[:open_select] : @is_open = nil
    params[:lesson] && params[:lesson][:trainer_select] != "" ? @trainer = Trainer.find(params[:lesson][:trainer_select].to_i) : @trainer = nil
    @lessons = Lesson.all
    if @is_open == "1"
      @lessons = @lessons.select{|l| !l.full?}
    end
    if @trainer
      @lessons = @lessons.select{|l| l.trainer == @trainer}
    end
    # if trainer
    #   @lessons = @lessons.select{|l| l.trainer == trainer}
    # end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/index.html.erb
<h1>Check out our professional level fitness lessons!</h1>

<%#=form_with method: :get, action: lessons_path do |f|%>
  <%#=f.label "Show all lessons taught by a certain trainer"%>
  <%#=f.collection_select :trainer_select, Trainer.all, :id, :name, :include_blank => "Do not filter"%><br>
<%=form_tag "lessons", method: :get do%>
  <%#=f.label "Show all lessons currently open for enrollment"%>
  <p>Filter lessons by trainer<%=collection_select :lesson, :trainer_select, Trainer.all, :id, :name, :include_blank => "Do not filter"%></p>
  Check this box to filter out full lessons <%=check_box_tag :open_select%>
  <%if @is_open || @trainer%>
    <%=link_to "Clear Filters", lessons_path%>
  <%end%>
  <%=submit_tag "Search"%>
  <%#=f.submit "Search!"%>
<%end%>

<%if @is_open || @trainer%>
  <h3>The following lessons are those which are <%="open for enrollment" if @is_open%> <%="and " if @is_open && @trainer%> <%="taught by #{@trainer.name}" if @trainer%>.</h3>
<%end%>

<!-- <ul> -->
<div id="wrap">
   <div id="content">

<%@lessons.each do |lesson|%>
  <li><%=link_to "#{lesson.name}", lesson%></li>
<%end%>
</div>
</div>
<!-- </ul> -->

app/views/lessons/show.html.erb
<h1><%=@lesson.name%> Class</h1>
<h3>Instructor: <%=link_to "#{@lesson.trainer.name}", @lesson.trainer%></h3>
<h5>This lesson is currently <%=@lesson.full? ? "full! All #{@lesson.capacity} slots have been filled by our members. Check back soon for cancellations!" : "available! Only #{@lesson.capacity - @lesson.users.count} spots left out of #{@lesson.capacity} so join quickly!"%></h5>

<%if !@lesson.full? && current_user%>
  <%=link_to "Click here to visit the lesson signup form", edit_user_path(current_user)%>
<%end%>

<p>Lesson description here in the future.</p>

<p>Join all of the following gym gods and goddesses who are enrolled in the <%=@lesson.name%> class right now!</p>

<!-- <ul> -->
<div id="wrap">
   <div id="content">
  <%@lesson.users.each do |u|%>
    <li><%=link_to u.name, u%></li>
  <%end%>
</div>
</div>
<!-- </ul> -->