config/routes.rb
Rails.application.routes.draw do
  get "/", to: "application#home", as: "root"

  get "/admin/analytics", to: "users#analytics", as: "analytics"

  get "/users/:id/downgrade_plan", to: "users#downgrade_plan", as: "downgrade"
  patch "/users/:id/downgrade_plan", to: "users#downgrade_plan"
  get "/users/:id/delete", to: "users#delete", as: "delete_user"
  get "/users/:id/goodbye", to: "users#goodbye", as: "goodbye"
  resources :trainers
  resources :lessons
  resources :class_plans
  resources :plans
  resources :users

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auto_login' => 'sessions#create_from_signup'


  # These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :lessons
  has_many :users, through: :lessons

  def students
    self.lessons.map{|l| l.users.map{|u| u.name}}.flatten.uniq
  end

  def all_class_roster_size
    self.lessons.map{|l| l.users.map{|u| u.name}}.flatten.count
  end

  def self.sorted_popularity
    Trainer.all.map{|t| [t, t.all_class_roster_size]}.sort_by{|i| i[1]}.reverse!
  end

  def trainer_revenue
    total = 0
    self.users.each do |user|
      relevant_lessons = user.lessons.select{|l| l.trainer == self}
      total += (user.plan.price.to_f / user.lessons.count)*relevant_lessons.count
    end
    total
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def index
    @trainers = Trainer.all
  end

  def show
    @trainer=Trainer.find(params[:id])
    @image = @trainer.name.downcase.split(" ").join("-") << ".jpg"
    STDERR.puts "****************#{@image}"
  end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/index.html.erb
<h1>List of Trainers</h1>
<!-- <ul> -->


<div id="wrap">
   <div id="content">
<%@trainers.each do |trainer|%>
<li><%=link_to trainer.name, trainer_path(trainer)%></li>
<%end%>
</div>
</div>
<!-- </ul> -->

app/views/trainers/show.html.erb
<h1>Trainer Info</h1>

<h1><%=@trainer.name%></h1>
<!-- < % =<img src="" alt="">%> -->
<%if @image%>
  <!-- <img src="< %=@image%>" alt=""> -->
  <img src="<%=asset_path(@image)%>" alt=""   height="20%" width="20%" id="littlepic" >
  <span id="pic"  >
    <!-- height:100%; -->
    <img src="<%=asset_path(@image)%>"  id="fullpageimage" style="width:100%; z-index: 2; position: absolute; left: 0px; top: 0px;">
    <!-- <img src="<%=asset_path(@image)%>"  id="fullpageimage" style="width:100%; z-index: 2; "> -->
  </span>

<%end %>
<h3>Lessons held by trainer:</h3>
<!-- <ul> -->
<div id="wrap">
   <div id="content">
  <%@trainer.lessons.each do |lesson|%>
  <li><%=link_to "#{lesson.name} held at #{lesson.time} in #{lesson.room}", lesson_path(lesson)%></li>
  <%end%>
</div>
</div>
<!-- </ul> -->






<script>
// var myIndex = 0;
carousel();

function carousel() {
    // var i;
    var x = document.getElementById("fullpageimage");
    // x.style.height = '100%';
    // for (i = 0; i < x.length; i++) {
    //    x[i].style.display = "none";
    // }
    // myIndex++;
    // if (myIndex > x.length) {myIndex = 1}
    // setTimeout(function(){x.style.display = "none";},2000); // Change image every 2 seconds
    // setTimeout(function(){x.style.width = '20%'; x.style.position="none";x.style.left="auto";x.style.top="auto";x.style.zIndex="1";},2000); // Change image every 2 seconds
    setTimeout(function(){x.style.display = 'none'; x.style.position="none";x.style.left="auto";x.style.top="auto";x.style.zIndex="1";
      var y = document.getElementById("pic");

      },2000); // Change image every 2 seconds
    // x.style.width = "20%";


}
</script>