config/routes.rb
Rails.application.routes.draw do
  get "/", to: "application#home", as: "root"

  get "/admin/analytics", to: "users#analytics", as: "analytics"

  get "/users/:id/downgrade_plan", to: "users#downgrade_plan", as: "downgrade"
  patch "/users/:id/downgrade_plan", to: "users#downgrade_plan"
  get "/users/:id/delete", to: "users#delete", as: "delete_user"
  get "/users/:id/goodbye", to: "users#goodbye", as: "goodbye"
  resources :trainers
  resources :lessons
  resources :class_plans
  resources :plans
  resources :users

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auto_login' => 'sessions#create_from_signup'


  # These routes will be for signup. The first renders a form in the browse, the second will
# receive the form and create a user in our database using the data given to us by the user.
  get '/signup' => 'users#new'
  # post '/users' => 'users#create'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav" style="text-align:center;">
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'Membership Plans', plans_path %></li>
  <li><%= link_to 'Lessons', lessons_path %></li>
  <li><%= link_to 'Trainer Team', trainers_path %></li>
  <li><%= link_to 'Members', users_path %></li>
  <%if session[:user_id] %>
    <li><%=link_to "| Welcome " + "#{User.find(session[:user_id]).username}", User.find(session[:user_id])%></li>
    <li><%=link_to "Logout |", logout_path%></li>

  <% else %>
    <li><%=link_to "Login", login_path%></li>
    <li> OR </li>
    <li> <%=link_to "Signup", signup_path%></li>
  <!-- if user_loggedin then show login name-->
  <%end%>
  <%if session[:user_id] && current_user.admin%>
    <li><%=link_to "Gym Analytics", analytics_path%></li>
  <%end%>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gym" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Gym" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <!-- < %= javascript_include_tag [
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ]%>
    < %= stylesheet_link_tag [
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" ]%> -->
      <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <img src="<%=asset_path('logo.png')%>" alt="" style="z-index: 1; position: absolute; left: 0px; top: 0px;">
      <%= yield %>
    </main>
    <!-- <iframe width="1" height="1" src="http://www.youtube.com/embed/
    yWUPMd9fJOs?autoplay=1&cc_load_policy=1" frameborder="0"
    allowfullscreen></iframe> -->
  </body>
</html>